# Generated by Django 4.1.1 on 2022-09-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=122),
            preserve_default=False,
        ),
    ]
